### ISSUE TITLE
kselftest: remove hard-coded assumptions about .tar.gz

### ISSUE THREAD

**Issue by khilman** [Linaro/test-definitions#195]
The kselftest definition currently assumes that the tarball built by the kernel is always in .gz format.  However, the kernel build process can make other compressed tarballs using the `FORMAT=` option when calling `make gen_tar`.

For example, in the kernel build
```
make -C tools/testing/selftests gen_tar FORMAT=.xz
```
will create `kselftest.tar.xz`

When no `FORMAT` is specified, the kernel default is `.gz` but using xz should still be an option for users of this test-plan.

**Comment by khilman** [comment]
@nareshkamboju @mwasilew thoughts?

**Comment by nareshkamboju** [comment]
@khilman you are right about the test assumption on .gz
IMOH, The problem can be solved by adding an extra params as FORMAT in kselftest.yaml and changing test code like unzip command and etc in kselftest.sh

**Comment by mwasilew** [comment]
I assume you're referring to https://github.com/Linaro/test-definitions/blob/master/automated/linux/kselftest/kselftest.sh#L140 and https://github.com/Linaro/test-definitions/blob/master/automated/linux/kselftest/kselftest.sh#L143 and https://github.com/Linaro/test-definitions/blob/master/automated/linux/kselftest/kselftest.sh#L145. I don't think we need to introduce any new variables to solve it. xz-utils is already part of dependencies. I propose to extract the file name from TESTPROG_URL and use it in the script.

**Comment by khilman** [comment]
Correct.  I you just extract the basename from the URL and have a recent version of tar + xz-utils, you can `tar -xaf` it will detect the compression type and do the right thing.
